FROM node:18-bullseye

RUN apt-get update && apt-get install -y python3 python3-pip

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN pip3 install -r requirements.txt

EXPOSE 5003

CMD ["npm", "start"]